### Get the student with the id in url
GET {{baseUrl}}/api/student/4

### Get the list of students
GET {{baseUrl}}/api/student/all

### Create a student
POST {{baseUrl}}/api/student
Content-Type: application/json

{
  "lastname": "test",
  "firstname": "test",
  "birthdate": "2009-09-09",
  "grade": 4
}

### Update a student
PUT {{baseUrl}}/api/student/4
Content-Type: application/json

{
  "lastname": "abc",
  "firstname": "def",
  "birthdate": "2004-04-04",
  "grade": 3
}

### Delete a student
DELETE {{baseUrl}}/api/student/4

